/**
 * Permission codes mirrored from the backend catalogue
 * (`LibraryConnect.Application/Common/Security/PermissionCodes.cs`).
 *
 * They drive menu visibility and button state only — the backend re-checks every request, so a
 * mismatch here can never widen access, at worst it hides something the user may in fact use.
 */
export const PERMISSIONS = {
  system: {
    groupView: 'SYSTEM.GROUP.VIEW',
    groupCreate: 'SYSTEM.GROUP.CREATE',
    groupUpdate: 'SYSTEM.GROUP.UPDATE',
    groupDelete: 'SYSTEM.GROUP.DELETE',
    groupPermission: 'SYSTEM.GROUP.PERMISSION',
    userView: 'SYSTEM.USER.VIEW',
    userCreate: 'SYSTEM.USER.CREATE',
    userUpdate: 'SYSTEM.USER.UPDATE',
    userDelete: 'SYSTEM.USER.DELETE',
    userResetPassword: 'SYSTEM.USER.RESET_PASSWORD',
    userLock: 'SYSTEM.USER.LOCK',
    userImport: 'SYSTEM.USER.IMPORT',
    parameterView: 'SYSTEM.PARAMETER.VIEW',
    parameterUpdate: 'SYSTEM.PARAMETER.UPDATE',
    auditView: 'SYSTEM.AUDIT.VIEW',
    auditExport: 'SYSTEM.AUDIT.EXPORT',
    auditSetting: 'SYSTEM.AUDIT.SETTING',
    backupView: 'SYSTEM.BACKUP.VIEW',
    backupCreate: 'SYSTEM.BACKUP.CREATE',
    backupRestore: 'SYSTEM.BACKUP.RESTORE',
    backupDelete: 'SYSTEM.BACKUP.DELETE',
    backupSetting: 'SYSTEM.BACKUP.SETTING',
    jobView: 'SYSTEM.JOB.VIEW',
  },
  catalogList: {
    view: 'CATALOG.LIST.VIEW',
    create: 'CATALOG.LIST.CREATE',
    update: 'CATALOG.LIST.UPDATE',
    delete: 'CATALOG.LIST.DELETE',
    import: 'CATALOG.LIST.IMPORT',
    export: 'CATALOG.LIST.EXPORT',
    merge: 'CATALOG.LIST.MERGE',
    customIndex: 'CATALOG.CUSTOM_INDEX.MANAGE',
  },
  cataloging: {
    bibView: 'CATALOG.BIB.VIEW',
    bibCreate: 'CATALOG.BIB.CREATE',
    bibUpdate: 'CATALOG.BIB.UPDATE',
    bibDelete: 'CATALOG.BIB.DELETE',
    bibApprove: 'CATALOG.BIB.APPROVE',
    bibImport: 'CATALOG.BIB.IMPORT',
    bibExport: 'CATALOG.BIB.EXPORT',
    bibVersionRestore: 'CATALOG.BIB.VERSION_RESTORE',
    marcDefinitionView: 'CATALOG.MARC_DEFINITION.VIEW',
    marcDefinition: 'CATALOG.MARC_DEFINITION.MANAGE',
    template: 'CATALOG.TEMPLATE.MANAGE',
    defaultValue: 'CATALOG.DEFAULT_VALUE.MANAGE',
    queueView: 'CATALOG.QUEUE.VIEW',
    queueAssign: 'CATALOG.QUEUE.ASSIGN',
    queueProcess: 'CATALOG.QUEUE.PROCESS',
    queueApprove: 'CATALOG.QUEUE.APPROVE',
    cardTemplate: 'CATALOG.CARD_TEMPLATE.MANAGE',
    cardPrint: 'CATALOG.CARD.PRINT',
    z3950Search: 'CATALOG.Z3950.SEARCH',
    z3950Target: 'CATALOG.Z3950.TARGET_MANAGE',
    oaiManage: 'CATALOG.OAI.MANAGE',
  },
  acquisition: {
    requestView: 'ACQ.REQUEST.VIEW',
    requestCreate: 'ACQ.REQUEST.CREATE',
    requestUpdate: 'ACQ.REQUEST.UPDATE',
    requestDelete: 'ACQ.REQUEST.DELETE',
    requestSubmit: 'ACQ.REQUEST.SUBMIT',
    requestApprove: 'ACQ.REQUEST.APPROVE',
    requestImport: 'ACQ.REQUEST.IMPORT',
    orderView: 'ACQ.ORDER.VIEW',
    orderCreate: 'ACQ.ORDER.CREATE',
    orderUpdate: 'ACQ.ORDER.UPDATE',
    orderApprove: 'ACQ.ORDER.APPROVE',
    orderReceive: 'ACQ.ORDER.RECEIVE',
    orderPrint: 'ACQ.ORDER.PRINT',
    handoverView: 'ACQ.HANDOVER.VIEW',
    handoverManage: 'ACQ.HANDOVER.MANAGE',
    itemView: 'ACQ.ITEM.VIEW',
    itemCreate: 'ACQ.ITEM.CREATE',
    itemUpdate: 'ACQ.ITEM.UPDATE',
    itemDelete: 'ACQ.ITEM.DELETE',
    itemInspect: 'ACQ.ITEM.INSPECT',
    itemLock: 'ACQ.ITEM.LOCK',
    itemMove: 'ACQ.ITEM.MOVE',
    itemDispose: 'ACQ.ITEM.DISPOSE',
    itemPrintBarcode: 'ACQ.ITEM.PRINT_BARCODE',
    itemPrintLabel: 'ACQ.ITEM.PRINT_LABEL',
    itemExport: 'ACQ.ITEM.EXPORT',
    warehouseView: 'ACQ.WAREHOUSE.VIEW',
    warehouseManage: 'ACQ.WAREHOUSE.MANAGE',
    libraryManage: 'ACQ.LIBRARY.MANAGE',
    inventoryView: 'ACQ.INVENTORY.VIEW',
    inventoryCreate: 'ACQ.INVENTORY.CREATE',
    inventoryScan: 'ACQ.INVENTORY.SCAN',
    inventoryClose: 'ACQ.INVENTORY.CLOSE',
    inventoryReport: 'ACQ.INVENTORY.REPORT',
    formTemplate: 'ACQ.FORM_TEMPLATE.MANAGE',
    reportView: 'ACQ.REPORT.VIEW',
    reportExport: 'ACQ.REPORT.EXPORT',
  },
  serial: {
    view: 'SERIAL.TITLE.VIEW',
    create: 'SERIAL.TITLE.CREATE',
    update: 'SERIAL.TITLE.UPDATE',
    delete: 'SERIAL.TITLE.DELETE',
    predict: 'SERIAL.ISSUE.PREDICT',
    receive: 'SERIAL.ISSUE.RECEIVE',
    claim: 'SERIAL.ISSUE.CLAIM',
    bind: 'SERIAL.ISSUE.BIND',
    article: 'SERIAL.ARTICLE.MANAGE',
    reportView: 'SERIAL.REPORT.VIEW',
  },
  interlibrary: {
    search: 'CATALOG.Z3950.SEARCH',
    targetManage: 'CATALOG.Z3950.TARGET_MANAGE',
    oaiManage: 'CATALOG.OAI.MANAGE',
    oaiHarvest: 'CATALOG.OAI.HARVEST',
  },
  digital: {
    view: 'DIGITAL.DOCUMENT.VIEW',
    upload: 'DIGITAL.DOCUMENT.UPLOAD',
    update: 'DIGITAL.DOCUMENT.UPDATE',
    delete: 'DIGITAL.DOCUMENT.DELETE',
    download: 'DIGITAL.DOCUMENT.DOWNLOAD',
    collection: 'DIGITAL.COLLECTION.MANAGE',
    requestView: 'DIGITAL.REQUEST.VIEW',
    requestApprove: 'DIGITAL.REQUEST.APPROVE',
    import: 'DIGITAL.DOCUMENT.IMPORT',
    export: 'DIGITAL.DOCUMENT.EXPORT',
    reportView: 'DIGITAL.REPORT.VIEW',
    accessLogView: 'DIGITAL.ACCESS_LOG.VIEW',
  },
  reader: {
    view: 'READER.PROFILE.VIEW',
    create: 'READER.PROFILE.CREATE',
    update: 'READER.PROFILE.UPDATE',
    delete: 'READER.PROFILE.DELETE',
    lock: 'READER.PROFILE.LOCK',
    extendCard: 'READER.CARD.EXTEND',
    printCard: 'READER.CARD.PRINT',
    cardTemplate: 'READER.CARD_TEMPLATE.MANAGE',
    import: 'READER.PROFILE.IMPORT',
    export: 'READER.PROFILE.EXPORT',
    resetPassword: 'READER.PROFILE.RESET_PASSWORD',
    violationManage: 'READER.VIOLATION.MANAGE',
    reportView: 'READER.REPORT.VIEW',
  },
  circulation: {
    policyView: 'CIRCULATION.POLICY.VIEW',
    policyManage: 'CIRCULATION.POLICY.MANAGE',
    loanCreate: 'CIRCULATION.LOAN.CREATE',
    loanReturn: 'CIRCULATION.LOAN.RETURN',
    loanRenew: 'CIRCULATION.LOAN.RENEW',
    loanView: 'CIRCULATION.LOAN.VIEW',
    holdManage: 'CIRCULATION.HOLD.MANAGE',
    fineView: 'CIRCULATION.FINE.VIEW',
    fineCollect: 'CIRCULATION.FINE.COLLECT',
    fineWaive: 'CIRCULATION.FINE.WAIVE',
    lockerManage: 'CIRCULATION.LOCKER.MANAGE',
    visitManage: 'CIRCULATION.VISIT.MANAGE',
    templateManage: 'CIRCULATION.TEMPLATE.MANAGE',
    reportView: 'CIRCULATION.REPORT.VIEW',
    reportExport: 'CIRCULATION.REPORT.EXPORT',
  },
  cms: {
    pageManage: 'CMS.PAGE.MANAGE',
    newsView: 'CMS.NEWS.VIEW',
    newsManage: 'CMS.NEWS.MANAGE',
    newsPublish: 'CMS.NEWS.PUBLISH',
    menuManage: 'CMS.MENU.MANAGE',
    bannerManage: 'CMS.BANNER.MANAGE',
    settingManage: 'CMS.SETTING.MANAGE',
    galleryManage: 'CMS.GALLERY.MANAGE',
    linkManage: 'CMS.LINK.MANAGE',
    reviewModerate: 'CMS.REVIEW.MODERATE',
  },
  course: {
    majorManage: 'COURSE.MAJOR.MANAGE',
    courseManage: 'COURSE.COURSE.MANAGE',
    documentLink: 'COURSE.DOCUMENT.LINK',
    reportView: 'COURSE.REPORT.VIEW',
  },
} as const;
