/**
 * Permission codes mirrored from the backend catalogue
 * (`LibraryConnect.Application/Common/Security/PermissionCodes.cs`).
 *
 * They drive menu visibility and button state only — the backend re-checks every request, so a
 * mismatch here can never widen access, at worst it hides something the user may in fact use.
 */
export const PERMISSIONS = {
  system: {
    groupView: 'SYSTEM.GROUP.VIEW',
    groupCreate: 'SYSTEM.GROUP.CREATE',
    groupUpdate: 'SYSTEM.GROUP.UPDATE',
    groupDelete: 'SYSTEM.GROUP.DELETE',
    groupPermission: 'SYSTEM.GROUP.PERMISSION',
    userView: 'SYSTEM.USER.VIEW',
    userCreate: 'SYSTEM.USER.CREATE',
    userUpdate: 'SYSTEM.USER.UPDATE',
    userDelete: 'SYSTEM.USER.DELETE',
    userResetPassword: 'SYSTEM.USER.RESET_PASSWORD',
    userLock: 'SYSTEM.USER.LOCK',
    userImport: 'SYSTEM.USER.IMPORT',
    parameterView: 'SYSTEM.PARAMETER.VIEW',
    parameterUpdate: 'SYSTEM.PARAMETER.UPDATE',
    auditView: 'SYSTEM.AUDIT.VIEW',
    auditExport: 'SYSTEM.AUDIT.EXPORT',
    auditSetting: 'SYSTEM.AUDIT.SETTING',
    backupView: 'SYSTEM.BACKUP.VIEW',
    backupCreate: 'SYSTEM.BACKUP.CREATE',
    backupRestore: 'SYSTEM.BACKUP.RESTORE',
    backupDelete: 'SYSTEM.BACKUP.DELETE',
    backupSetting: 'SYSTEM.BACKUP.SETTING',
    jobView: 'SYSTEM.JOB.VIEW',
  },
  catalogList: {
    view: 'CATALOG.LIST.VIEW',
    create: 'CATALOG.LIST.CREATE',
    update: 'CATALOG.LIST.UPDATE',
    delete: 'CATALOG.LIST.DELETE',
    import: 'CATALOG.LIST.IMPORT',
    export: 'CATALOG.LIST.EXPORT',
    merge: 'CATALOG.LIST.MERGE',
    customIndex: 'CATALOG.CUSTOM_INDEX.MANAGE',
  },
  cataloging: {
    bibView: 'CATALOG.BIB.VIEW',
    bibCreate: 'CATALOG.BIB.CREATE',
    bibUpdate: 'CATALOG.BIB.UPDATE',
    bibDelete: 'CATALOG.BIB.DELETE',
    bibApprove: 'CATALOG.BIB.APPROVE',
    bibImport: 'CATALOG.BIB.IMPORT',
    bibExport: 'CATALOG.BIB.EXPORT',
    marcDefinitionView: 'CATALOG.MARC_DEFINITION.VIEW',
    marcDefinition: 'CATALOG.MARC_DEFINITION.MANAGE',
    template: 'CATALOG.TEMPLATE.MANAGE',
    defaultValue: 'CATALOG.DEFAULT_VALUE.MANAGE',
    queueView: 'CATALOG.QUEUE.VIEW',
    cardTemplate: 'CATALOG.CARD_TEMPLATE.MANAGE',
    cardPrint: 'CATALOG.CARD.PRINT',
    z3950Search: 'CATALOG.Z3950.SEARCH',
    z3950Target: 'CATALOG.Z3950.TARGET_MANAGE',
    oaiManage: 'CATALOG.OAI.MANAGE',
  },
  acquisition: {
    requestView: 'ACQ.REQUEST.VIEW',
    requestApprove: 'ACQ.REQUEST.APPROVE',
    orderView: 'ACQ.ORDER.VIEW',
    handoverView: 'ACQ.HANDOVER.VIEW',
    itemView: 'ACQ.ITEM.VIEW',
    itemPrintBarcode: 'ACQ.ITEM.PRINT_BARCODE',
    warehouseView: 'ACQ.WAREHOUSE.VIEW',
    inventoryView: 'ACQ.INVENTORY.VIEW',
    reportView: 'ACQ.REPORT.VIEW',
  },
  serial: {
    view: 'SERIAL.TITLE.VIEW',
    receive: 'SERIAL.ISSUE.RECEIVE',
    article: 'SERIAL.ARTICLE.MANAGE',
    reportView: 'SERIAL.REPORT.VIEW',
  },
  digital: {
    view: 'DIGITAL.DOCUMENT.VIEW',
    upload: 'DIGITAL.DOCUMENT.UPLOAD',
    collection: 'DIGITAL.COLLECTION.MANAGE',
    requestView: 'DIGITAL.REQUEST.VIEW',
    reportView: 'DIGITAL.REPORT.VIEW',
  },
  reader: {
    view: 'READER.PROFILE.VIEW',
    create: 'READER.PROFILE.CREATE',
    printCard: 'READER.CARD.PRINT',
    import: 'READER.PROFILE.IMPORT',
    reportView: 'READER.REPORT.VIEW',
  },
  circulation: {
    policyView: 'CIRCULATION.POLICY.VIEW',
    loanCreate: 'CIRCULATION.LOAN.CREATE',
    loanReturn: 'CIRCULATION.LOAN.RETURN',
    loanView: 'CIRCULATION.LOAN.VIEW',
    holdManage: 'CIRCULATION.HOLD.MANAGE',
    fineView: 'CIRCULATION.FINE.VIEW',
    lockerManage: 'CIRCULATION.LOCKER.MANAGE',
    reportView: 'CIRCULATION.REPORT.VIEW',
  },
  cms: {
    pageManage: 'CMS.PAGE.MANAGE',
    newsView: 'CMS.NEWS.VIEW',
    menuManage: 'CMS.MENU.MANAGE',
    bannerManage: 'CMS.BANNER.MANAGE',
    settingManage: 'CMS.SETTING.MANAGE',
    galleryManage: 'CMS.GALLERY.MANAGE',
  },
  course: {
    majorManage: 'COURSE.MAJOR.MANAGE',
    courseManage: 'COURSE.COURSE.MANAGE',
    documentLink: 'COURSE.DOCUMENT.LINK',
    reportView: 'COURSE.REPORT.VIEW',
  },
} as const;
